# Generated by Django 4.1 on 2023-02-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictedHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game", models.CharField(max_length=255)),
                ("team_1", models.CharField(max_length=255)),
                ("team_2", models.CharField(max_length=255)),
                ("result", models.CharField(max_length=255)),
                ("predicted_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
